### PR TITLE
elasticsearch: Fix invenio.config import

### PR DESCRIPTION
**Pull request by ddaze**
Signed-off-by: David Zerulla ddaze@outlook.de

### CODE REVIEW

**Comment by ddaze** [comment]
cc @kasioumis

**Comment by egabancho** [comment]
@ddaze can you refresh me why this is  needed?

**Comment by ddaze** [comment]
The `elasticsearch_logging` module is imported in `invenio/modules/miscutil/lib/__init__.py`,
and is then trying to access the invenio.config.
This breaks inveniocfg when the config should get created.
(Running instances with a working config are not affected by this.)

I will improve the pr and also add a more specific commit message.

**Comment by ddaze** [comment]
Ping @egabancho, done.

**Comment by egabancho** [comment]
closed via a32bca836efe24e7e137c065b828958753a6928e

**Comment by ludmilamarian** [comment]
@egabancho is this the commit you were talking IRL? it needs to go to Invenio as well, if lumberjack is integrated, right?

**Comment by egabancho** [comment]
Yes! If we reopen the lumberjack one probably we can simply integrate this one there

**Pull request closed without merging**
