### PR TITLE
WebComment: remove unnecessary exceptions

### PR DESCRIPTION
**Pull request by drjova**
- Removes unnecessary `raise InvenioWebCommentWarning`,
  `raise InvenioWebCommentError` and `register_exception`.
- Removes unnecessary messages from the `webinterface`

Signed-off-by: Harris Tzovanakis me@drjova.com

### CODE REVIEW

**Comment by egabancho** [comment]
https://github.com/inveniosoftware/invenio/pull/2801

**Comment by egabancho** [comment]
@kasioumis should I integrate this now or should I wait for your changes?

**Comment by kasioumis** [comment]
@egabancho It shouldn't really be touching any of the things Makis did, so it should be safe to integrate now. Is this going into master too anytime soon? If it goes in master then I can rebase and resolve any conflicts there, otherwise we'll have to resolve them when merging with cds-ops..

**Comment by egabancho** [comment]
There is already a PR on master but, probably, we will have to resolve the conflicts, if any, here as we will integrate your branch (Makis' work) first

**Pull request merged**
