### PR TITLE
Added the feature to find the normalized loan period to find the bott…

### PR DESCRIPTION
**Pull request by chakshuahuja**
…leneck of the availability of books

### CODE REVIEW

**Comment by ludmilamarian** [comment]
@egabancho do you remember the state of this PR? integrated?

**Comment by egabancho** [comment]
I don't remember anything about it, definitely not deployed in prod. 
Maybe @mvesper can tell us something about it ...

**Comment by ludmilamarian** [comment]
@mvesper, can you take a look? Is this still needed, or it can be closed? (it introduces a lot of code, so it will need to be reviewed)

**Comment by ludmilamarian** [comment]
As we are in feature freeze for the current version of Invenio/CDS, these should go into Invenio 3/CDSLabs if they are still needed.

**Pull request closed without merging**
