### PR TITLE
Master fulltext by default

### PR DESCRIPTION
**Pull request by pglauner**
Pending discussion on problem with Ludmila on similar-to-recid ranking, seems to be independent from Solr

### CODE REVIEW

**Comment by pglauner** [comment]
Latest master does similar-to-recid ranking in wrong order: /search?p=recid%3A77&rm=wrd
This is independent from my branch. Therefore, please go ahead integrating it.

I will investigate this problem soon.

**Comment by pglauner** [comment]
Ludmila, Jenkins is happy:
https://jenkins.invenio-software.org/job/invenio-master-ondemand/447/testReport/

**Comment by ludmilamarian** [comment]
I'm merging it to cds-ops, but I have a comment for the Invenio merge by quickly looking at the diff: I don't see the gain of passing around the full kwargs dictionary, when only one item is needed, the search interface type - it's heavy and unclear. Plus, this can be quite dangerous (somebody can start modifying kwargs in one of these functions, without knowing that other functions are heavily relying on it). Moreover, we're passing many values twice, explicitly and via kwargs (for ex: of, and kwargs['of']) which might be very confusing for the future.

**Comment by egabancho** [comment]
https://github.com/inveniosoftware/invenio/pull/2768

**Pull request merged**
