### PR TITLE
WebSubmit: fix missing authors in emails

### PR DESCRIPTION
**Pull request by drjova**
- Fixes missing authors from emails on submissions with author autocompletion.

Signed-off-by: Harris Tzovanakis me@drjova.com

### CODE REVIEW

**Comment by egabancho** [comment]
Whenever you can, remember to remove the "legacy" field as we decided to update the submission workflow instead

**Comment by drjova** [comment]
:+1:  done

**Comment by egabancho** [comment]
Merged manually as it depends on out prod branch

**Comment by ludmilamarian** [comment]
This looks as a fix for author autocompte that was also merged into the legacy branch, thus I think it would deserve an invenio PR, WDYT? @drjova @egabancho

**Pull request closed without merging**
