### PR TITLE
WebSearch: tabs miss language parameter

### PR DESCRIPTION
**Pull request by drjova**
- FIX Adds the proper language parameter on tabs if the user has
  selected different language from the browser preferred. (closes
  #308)

Signed-off-by: Harris Tzovanakis me@drjova.com

### CODE REVIEW

**Comment by egabancho** [comment]
Can you make this one on top of Invenio instead?

**Comment by drjova** [comment]
done!

**Comment by egabancho** [comment]
Can you make a PR for Invenio? and rebase :wink:

**Comment by egabancho** [comment]
https://github.com/inveniosoftware/invenio/pull/3395

**Pull request closed without merging**
