### PR TITLE
MiscUtil: run query get table update time on slave

### PR DESCRIPTION
**Pull request by ntarocco**

### CODE REVIEW

**Review by ludmilamarian — COMMENTED** [review]
Just one thing that I thought of now: isn't it possible in the case when the slave is behind master, that the `get_table_update_time` would report false information if performed on slave?

**Comment by egabancho** [comment]
The case of "slave behind master" is really rare, if it happens you will get an email telling you so, and the task using this function will pick up next time (IMHO)

**Comment by ludmilamarian** [comment]
@egabancho thanks! reading a bit I am still not convinced that slave behind master is rare but I agree that the function is not critical, thus being a few seconds behind from time to time, won't have a negative impact

**Review by ludmilamarian — APPROVED** [review]

**Comment by egabancho** [comment]
I meant rare in the eyes of the script that checks if slave is behind master, I think it's a high number of seconds which really means that something is going on, otherwise the script considers it normal. (I should I said this before)

I don't know what it's be average value of it, it might be nice to get it somehow ☺️

**Pull request merged**
