### PR TITLE
Youtube

### PR DESCRIPTION
**Pull request by drjova**
Bibencode: Video: Push video to youtube
- More mime types
- Clean the javascript
- Better documentation
- Fix authentication result object check

### CODE REVIEW

**Comment by kasioumis** [comment]
@drjova & @ludmilamarian I see that this is not yet deployed? Should we merge or not yet?

**Comment by egabancho** [comment]
@drjova should I integrate this?

**Comment by ludmilamarian** [comment]
It's deployed on production, so I don't see why not.. @drjova can you make a PR for Invenio? Will it work for master, or it's only for legacy for now?

**Comment by drjova** [comment]
@egabancho  @ludmilamarian I will prepare a PR for Invenio, for now it's only for legacy thanks!

**Pull request merged**
